import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import logo from "../../public/logo.png";
import LoadingButton from "@mui/lab/LoadingButton";
import { signedRequest } from "@/utils/signedRequest";
import { AssetAccount } from "@/utils/types";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [accessKey, setAccessKey] = useState("-");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const interval = setInterval(async () => {
      const key = localStorage.getItem("access_key");
      setAccessKey(key || "");
      if (!key) {
        router.push("/login");
      }
    }, 10000);
    return () => clearInterval(interval);
  }, [accessKey, router]);

  const handleCreateWallet = async () => {
    setLoading(true);
    signedRequest<AssetAccount>(
      "POST",
      "/api/accounts",
      "POST",
      "/assets/asset-accounts",
      JSON.stringify({ assetSymbol: "MATIC" })
    )
      .then((assetAccount: AssetAccount) => {
        console.log("Account created: " + JSON.stringify(assetAccount));
        localStorage.setItem("walletID", assetAccount.id);
        router.push("wallet");
      })
      .catch((error) => {
        console.log(error);
      });
  };

  return (
    <>
      <Head>
        <title>Dfns Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image src={logo} alt="logo" width={411} height={200} />
        Your user has logged in and is ready to create a wallet...
        <LoadingButton
          variant="contained"
          loading={loading}
          onClick={handleCreateWallet}
        >
          Create Wallet
        </LoadingButton>
      </main>
    </>
  );
}
