import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import logo from "../../public/logo.png";
import LoadingButton from "@mui/lab/LoadingButton";
import { signedRequest } from "@/utils/signedRequest";
import { PaymentSuccess } from "@/utils/types";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TextField from "@mui/material/TextField";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import IconButton from "@mui/material/IconButton";

const inter = Inter({ subsets: ["latin"] });

export default function Wallet() {
  const router = useRouter();
  const [accessKey, setAccessKey] = useState("-");
  const [loading, setLoading] = useState(false);
  const [balance, setBalance] = useState(0);
  const [hasBalance, setHasBalance] = useState(true); // 0 was showing up in the UI - this fixed it
  const [walletID, setWalletID] = useState();
  const [walletAddress, setWalletAddress] = useState("");

  // Set the access key JWT from local storage for use in API calls
  useEffect(() => {
    const interval = setInterval(async () => {
      const key = localStorage.getItem("access_key");
      setAccessKey(key || "");
      if (!key) {
        router.push("/login");
      }
    }, 10000);
    setWalletID(localStorage.getItem("walletID") as any);
    setWalletAddress(localStorage.getItem("address") as any);
    return () => clearInterval(interval);
  }, [accessKey, router]);

  // Get the wallet address and balance
  useEffect(() => {
    if (!accessKey || accessKey === "-" || !walletID) {
      return;
    }
    // Get wallet address
    let endpoint = `/api/accounts/${walletID}`;
    let options = {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessKey}`,
      },
    };
    fetch(endpoint, options)
      .then(async (response) => {
        const address = (await response.json()).address;
        localStorage.setItem("address", address || "");
        setWalletAddress(address);
      })
      .catch((error) => {
        toast.error("Couldn't get address: ", error);
      });

    // Get wallet balance
    endpoint = `/api/accounts/${walletID}/balance`;
    options = {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessKey}`,
      },
    };
    fetch(endpoint, options)
      .then(async (response) => {
        const maxUnitBalance = (await response.json()).maxUnitBalance;
        setBalance(maxUnitBalance);
      })
      .catch((error) => {
        toast.error("Couldn't get balance: ", error);
      });
  }, [accessKey, walletID]);

  // Demonstrate a simple asset transfer with hardcoded values
  const handleTransfer = async () => {
    setLoading(true);
    toast.info("Transfering funds back...", {
      position: "bottom-center",
      autoClose: 3000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "light",
    });

    signedRequest<PaymentSuccess>(
      "POST",
      `/api/accounts/${walletID}/transfers`,
      "POST",
      `/assets/asset-accounts/${walletID}/payments`,
      // Hardcoding transfer values for the demo
      JSON.stringify({
        receiver: {
          kind: "BlockchainWalletAddress",
          address: "0xE0765280dB8dbbD55342D337fd26B2e711D253af",
        },
        assetSymbol: "ETH",
        amount: ".001",
      })
    )
      .then((payment: PaymentSuccess) => {
        console.log(payment);
        setHasBalance(false);
        toast.success("Transfer Completed!", {
          position: "bottom-center",
          autoClose: 1000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "light",
        });
      })
      .catch((error) => {
        console.log(error);
      });
  };

  // Copy the wallet address when the icon is clicked
  const handleCopy = () => {
    navigator.clipboard.writeText(walletAddress);
    toast.success("Copied!", {
      position: "bottom-center",
      autoClose: 1000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "light",
    });
  };

  return (
    <>
      <Head>
        <title>Dfns Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ToastContainer
          position="bottom-center"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <Image src={logo} alt="logo" width={410} height={200} />
        <div className="vflex">
          <p>Here&lsquo;s your wallet address:</p>
          <div className="hflex">
            <TextField
              disabled
              sx={{ width: "40ch" }}
              label={walletAddress}
              variant="outlined"
            />
            <IconButton onClick={handleCopy}>
              <ContentCopyIcon />
            </IconButton>
          </div>
          <h2> Balance: {balance} ETH</h2>
        </div>
        {hasBalance && (
          <LoadingButton
            variant="contained"
            loading={loading}
            onClick={handleTransfer}
          >
            Transfer
          </LoadingButton>
        )}
      </main>
    </>
  );
}
